name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Docker Run Action
        # You may pin to the exact commit or the version.
        # uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185
        uses: addnab/docker-run-action@v3
        with:
          # Image
          image: ghcr.io/dixon2678/binanceapi-el:main
          # Registry
          registry: ${{ env.REGISTRY }}
          # Username
          username: ${{ github.actor }}
          # Password
          password: ${{ secrets.GITHUB_TOKEN }}
